Refactoring (wip)
manala/ansible-role-php pull request #5
Opened 2016-11-20 13:21 UTC by nervo

2017-01-18 22:48 UTC, hyvs requested changes
first reading ⭐️

2017-01-18 22:48 UTC, hyvs commented on README.md
> +| `manala_php_version`                          | ~                           | String|Int|Float | Php version                                             |
Be aware that `|` in `String|Int|Float` breaks markdown preview

2017-01-18 22:48 UTC, hyvs commented on tasks/configs.yml
> +  register: __manala_php_configs_global_exclusive_find_result
Should be named `__manala_php_configs_exclusive_find_result` ?

2017-01-18 22:48 UTC, hyvs commented on tasks/configs.yml
> +    - php fpm restart
We should not restart `php fpm` when others sapi configs are modified.

2017-01-18 22:48 UTC, hyvs commented on tasks/configs.yml
> +  with_items: "{{ __manala_php_configs_global_exclusive_find_result.stdout_lines|default([]) }}"
Same here.

2017-02-01 09:22 UTC, nervo commented on tasks/configs.yml
> +    - php fpm restart
Interesting point. I've digged a little, and fpm is the *only* sapi having an attached service. Regarding the fact that we can not (or do we ?) select what to notify, i notify onnly fpm, and check is fpm has been selected in the handler itself.
Another approach could be just to notify an agnostic "php restart", and check fpm in the handler too. Would you prefer ?

2017-02-01 09:23 UTC, nervo commented on tasks/configs.yml
> +  register: __manala_php_configs_global_exclusive_find_result
Wo, nice catch

2017-02-01 09:24 UTC, nervo commented on README.md
> +| `manala_php_version`                          | ~                           | String|Int|Float | Php version                                             |
Fixed (comma instead of pipe)

2017-02-01 09:24 UTC, nervo commented on tasks/configs.yml
> +  with_items: "{{ __manala_php_configs_global_exclusive_find_result.stdout_lines|default([]) }}"
Same wo

2017-02-03 10:01 UTC, nervo commented
Wow, what an amazing piece of ~~crap~~ code, @nervo !

2017-02-03 10:01 UTC, nervo commented
Oh, thank you, i'm just doing my job !

2017-02-03 10:02 UTC, nervo commented
AUTO MEEEEERGE !
![](http://i.imgur.com/elGGP7e.gif)

2017-02-03 10:02 UTC, merged

2017-02-03 10:03 UTC, chalasr commented
Really, really nice job @nervo (hope @hyvs doesn't shot me, he requested changes)